### ISSUE TITLE
Error Message after "Apply" on Control WaterColorBot Extension

### ISSUE THREAD

**Issue by ckwallace** [evil-mad/wcb-ink#43]
In Inkscape, when I go to the extension menu> Control WaterColorBot extension> the window appears>  I click "apply"> it gives this error message:

Inkscape has received additional data from the script executed.  The script did not return an error, but this may indicate the results will not be as expected.

Traceback (most recent call last):
  File "wcb.py", line 1843, in <module>
    e.affect()
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 268, in affect
    self.effect()
  File "wcb.py", line 374, in effect
    self.plotToWCB()
  File "wcb.py", line 880, in plotToWCB
    self.recursivelyTraverseSvg( self.svg, self.svgTransform )
  File "wcb.py", line 1057, in recursivelyTraverseSvg
    w = float( node.get( 'width' ) )
ValueError: invalid literal for float(): 100%

My WaterColorBot is plugged into a power source and my laptop.  I have Inkscape and the Control WaterColorBot extension downloaded. I have restarted the laptop several times and unplugged the bot several times. Each time I open the test file with some shapes and font to test the above message appears and the device does not print. What can I do to resolve this message? Thank you for any help!

**Comment by oskay** [comment]
On first inspection, it _appears_ that there is an issue with the format of the SVG file that you are trying to print. It looks like a rectangle is specified with width "100%" in a way that 

You could confirm this by trying to print one of our example files; you can leave the brush out to save paper and ink.

If it is indeed the case that the issue is with this file rather than the machine in general, then (1) can you please say how the file was generated? And (2) you might consider sending the file to us, to see if we might be able to work with it.  From what I can see, it looks as perhaps the width of a rectangle has been specified as "100%" at a place where we are expecting there to be a pure (unitless) number.

**Comment by ckwallace** [comment]
I generated the file with the test1 sample that comes with the extension (because it comes preformatted) and I added shapes to that file (a star, a rectangle, a complex typeface) just to see the outcome. 

I just tried the happy birthday sample file and that worked fine. I think I still need to know why the error occurred because I will be using this device and software for programs and will need to learn more about troubleshooting these issues.

If you could look at the file and tell me what to fix, that would be great! How do I send it in, as this portal does not support svg? Thanks again.

**Comment by oskay** [comment]
Perhaps you could try deleting one of the shapes at a time, to reduce it down to a single object that is causing the problem. (If I had to guess, it was the rectangle.)

I have tried adding stars, rectangles, and text (via fonts) to the testplot1.svg example file, and I am not able to reproduce the error here.

One thing that you might try is selecting from the menus: 
Edit > Select all in all layers
Path > Object to path

**Comment by oskay** [comment]
This issue tracker does not support SVG files-- if you could email it to us, that would be better.

**Comment by ckwallace** [comment]
Sorry for the delay on this. If you could look at this file and let me know
how to troubleshoot for printing on the watercolorbot I would be very
grateful!

Thank you for any help!



*Casey Wallace* | Administrative Support Librarian
*Gwinnett County Public Library*
770-822-5326 | cwallace@gwinnettpl.org
www.gwinnettpl.org
<#UNIQUE_ID_SafeHtmlFilter_> <https://facebook.com/GwinnettLibrary>
<https://twitter.com/GwinnettLibrary>
<https://youtube.com/user/GwinnettLibrary>

**Comment by oskay** [comment]
You said "this file" but there wasn't anything attached in your comment here. Again, please contact us directly by e-mail (our contact info is here: http://shop.evilmadscientist.com/about ), and include zipped copy of the SVG file.

**Comment by ckwallace** [comment]
OK, I guess my attachment here didn't take.  There isn't an upload field in
the contact us portal, so hopefully if someone responds to the initial
inquiry I can reply with the file.

Sorry for the complications. Thanks for your help.



*Casey Wallace* | Administrative Support Librarian
*Gwinnett County Public Library*
770-822-5326 | cwallace@gwinnettpl.org
www.gwinnettpl.org
<#UNIQUE_ID_SafeHtmlFilter_> <https://facebook.com/GwinnettLibrary>
<https://twitter.com/GwinnettLibrary>
<https://youtube.com/user/GwinnettLibrary>

**Comment by oskay** [comment]
Again, you can send an attachment _by email_.  :)

**Comment by ckwallace** [comment]
Is that the contact@evilmadscientist.com address? It's on the picture but
not linked on the contact page, so I missed it. The email link goes
straight to the contact us portal.



*Casey Wallace* | Administrative Support Librarian
*Gwinnett County Public Library*
770-822-5326 | cwallace@gwinnettpl.org
www.gwinnettpl.org
<#UNIQUE_ID_SafeHtmlFilter_> <https://facebook.com/GwinnettLibrary>
<https://twitter.com/GwinnettLibrary>
<https://youtube.com/user/GwinnettLibrary>

**Comment by oskay** [comment]
Yes, you can send e-mail to the address listed on that page.

**Comment by ckwallace** [comment]
Thank you!



*Casey Wallace* | Administrative Support Librarian
*Gwinnett County Public Library*
770-822-5326 | cwallace@gwinnettpl.org
www.gwinnettpl.org
<#UNIQUE_ID_SafeHtmlFilter_> <https://facebook.com/GwinnettLibrary>
<https://twitter.com/GwinnettLibrary>
<https://youtube.com/user/GwinnettLibrary>

**Comment by oskay** [comment]
I've received the file.

I'm not sure exactly what you did to generate this file-- it is not obvious that it is derived from one of our templates. If it was taken from our template, you somehow managed to delete all of the named layers-- which are normally used in printing. In the future, please consider using "File > Templates..." to find and open the WaterColorBot template.  There is also some hint that you may have started with (or added?) some clipart from openswatchbook, which is often a source of files with errors.

The error was caused by an error in the definition of a giant invisible rectangle (a vestigial bounding box of some sort?), spanning the outline of the document. This error* went away when I deleted it.

To remove this rectangle, select Edit > Select All, deselect (shift-click) all of the parts that you do not want to remove, and then click Delete.

 *You will find additional (well understood) errors after you remove the mysterious invisible rectangle.  There is text (and other objects) that need to be converted to paths (lines) before drawing, and you do not have anything in numbered layers. 

Please read through our documentation about using wcb-ink:  http://wiki.evilmadscientist.com/Inkscape_and_WaterColorBot

You may also prefer to start with a more automated painting program, such as RoboPaint.
