### ISSUE TITLE
Getting python errors on OSX w/ 1.3.2

### ISSUE THREAD

**Issue by tobiasboyd** [evil-mad/wcb-ink#44]
When I click Apply (for anything), I get the following error:

```Traceback (most recent call last):
  File "wcb.py", line 1586, in <module>
    e.affect()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 265, in affect
    self.getposinlayer()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 207, in getposinlayer
    x = self.unittouu( xattr[0] + 'px' )
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 351, in unittouu
    return retval * (self.__uuconv[u.string[u.start():u.end()]] / self.__uuconv[self.getDocumentUnit()])
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 304, in getDocumentUnit
    p = param.match(svgwidth)
TypeError: expected string or buffer```

**Comment by oskay** [comment]
The error that you are seeing is in "inkex.py" -- the core Inkscape file that manages its extensions.  

Are other extensions working? I would test Extensions > Render > Gear, for example.

If they are working, then please try again with one of our Inkscape example files-- such as the cherry blossoms example: http://www.thingiverse.com/thing:133279

If they are not working, then is there any chance that you have forced a system path such that Inkscape is running its extensions through python 3?

**Comment by tobiasboyd** [comment]
Other extensions do work, but the file I was trying to print was pretty complex. I have gotten simpler images to work now, though with some gotchas, for example:
![screen shot 2016-01-29 at 11 49 40 am](https://cloud.githubusercontent.com/assets/1182465/12693726/d957758e-c6c7-11e5-95af-04f341d8122e.png)

**Comment by oskay** [comment]
OK, if extensions are otherwise working, then something else is amiss, and we should be able to fix it. 

Complexity itself should not be a problem-- we have not (yet) come across a file that didn't work because it was too big or complicated. We've often printed files with 10,000 objects, and on occasion deeply nested files that took all day to draw-- just from the sheer amount of lines to be drawn.

The error "unable to draw <description> object" warning is (so far as I can see) correct behavior. The extension will try to draw any path object. It can also draw quite a few (but not all) standard object types-- things like polygons, circles, and rectangles. For any object that it does not recognize or knows that it cannot draw, it is supposed to produce a warning (giving you the hint to convert everything to paths) and move onto the next object. (This is not an error; just a warning to the user that an object was skipped.)

If I understand what I'm seeing, your drawing contains a `<description>` object, which is not a standard SVG tag, and so it does produce a warning. If you had used the standard [`<desc>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/desc) or [`<title>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title) tag instead, the extension would have recognized and passed by that object without a warning.

If you do have a file that produces an error, one option would be to send us the file to see if we could reproduce it ourselves. If you would like to do that, I would recommend zipping the SVG file and sending it to us by e-mail.

**Comment by oskay** [comment]
A little more research on the "pretty complex" front: We did have some reports about five years ago of a similar problem (on the EggBot project), when Inkscape internally crashed (!) when fed a long enough path. I don't know if this bug is still in Inkscape, nor if this is related to what you were seeing.

Our interpretation of issue, back then, this was that the file (automatically generated) did not follow best practices for SVG file format with large amounts of path data:

> "Path data can contain newline characters and thus can be broken up into multiple lines to improve readability. Because of line length limitations with certain related tools, it is recommended that SVG generators split long path data strings across multiple lines, with each line not exceeding 255 characters. Also note that newline characters are only allowed at certain places within path data."

http://www.w3.org/TR/SVG/paths.html

If you are generating the data yourself, I would recommend placing each new coordinate pair of the SVG path file on its own line.

**Comment by oskay** [comment]
Haven't heard back, so I'm going to close this issue for the time being. Please feel free to reopen it if you can find a file to send us that can reproduce the issue.
